# EXCEPTION HANDLING SELENIUM

# -------------------------------------------------------------

# 1.Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [1]:
# Importing libraries
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

In [2]:
# Importing warings and ignoring waring if any present
import warnings
warnings.filterwarnings('ignore')

In [3]:
# connect to webdriver
driver = webdriver.Chrome("chromedriver.exe")

# get webpage
driver.get("https://www.amazon.in/")
driver.maximize_window()
time.sleep(2)

In [4]:
# search the user input product
search_bar = driver.find_element(By.ID,"twotabsearchtextbox")    
search_bar.clear()                                               
search_bar.send_keys(input('Enter the product you want to search : '))
time.sleep(3)
driver.find_element(By.XPATH,'//div[@class="nav-search-submit nav-sprite"]/span/input').click()

Enter the product you want to search : LAPTOP

# 2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [ ]:
# b_name=[]#Brand name
product_name=[]#Product Name
price=[]#Price
ret_exchange=[]#return/Exchange
exp_delivery=[]#Expected delivery
availability=[]#Availability
product_url=[]
urls=[]
for i in range(0,3):
    if i==0:
        p_urls=driver.find_elements(By.XPATH,"//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
    if i==1:
        n_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[1]/div/span[3]/div[2]/div[29]/div/div/span/a[1]')
        n_button.click()
        time.sleep(2)
        p_urls=driver.find_elements(By.XPATH,"//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
    # selecting and clicking next page
    if i==2:
        n_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[1]/div[1]/div/span[3]/div[2]/div[28]/div/div/span/a[3]')
        n_button.click()
        time.sleep(2)
        p_urls=driver.find_elements(By.XPATH,"//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a")
            
            

    for i in p_urls:
        urls.append(i.get_attribute('href'))

    
for i in urls:
    driver.get(i)
    time.sleep(2)
#scraping data for brand name
    try:
        bran=driver.find_element(By.XPATH,"//a[@id='bylineInfo']")
        b_name.append(bran.text)
    except NoSuchElementException as e:
        b_name.append("--")

#scraping data for product name
    try:
        prod=driver.find_element(By.XPATH,"//h1[@id='title']/span")
        product_name.append(prod.text)
    except NoSuchElementException as e:
        product_name.append("--")


#scraping data for price
    try:
        pri=driver.find_element(By.XPATH,"//div[@id='apex_desktop']/div/div/table/tbody/tr[2]/td[2]/span/span[2]")
        price.append(pri.text)
    except NoSuchElementException as e:
            price.append("--")

#scaping data for return
    try:
        retu=driver.find_element(By.XPATH,"//div[@id='RETURNS_POLICY']/span/div[2]/a")
        ret_exchange.append(retu.text)
    except NoSuchElementException as e:
        ret_exchange.append("--")

#scraping data for expected delivery
    try:
        deliv=driver.find_element(By.XPATH,"//div[@id='ddmDeliveryMessage']/b")
        exp_delivery.append(deliv.text)
    except NoSuchElementException as e:
        exp_delivery.append("--")

#scraping data for availability
    try:
        avail=driver.find_element(By.XPATH,"//div[@id='availability']/span")
        availability.append(avail.text)
    except NoSuchElementException as e:
        availability.append("--")

In [8]:

print(len(availability),len(b_name),len(product_name),len(ret_exchange),len(exp_delivery),len(availability),len(price),len(urls))

69 69 69 69 69 69 69 69

In [9]:
#Placing everything into dataframe
df=pd.DataFrame({"Brand Name":b_name,"Product":product_name,"Price":price,"Return/Exchange":ret_exchange,"Expected Delivery":exp_delivery,"Availability":availability})#"Product Url":urls})
df

,Brand Name,Product,Price,Return/Exchange,Expected Delivery,Availability
0,Visit the HP Store,HP 15s-Ryzen 3 5300U 8GB SDRAM/256GB SSD 15.6i...,--,7 Days Replacement,--,In stock.
1,Visit the LG Store,LG Gram 17 Intel 10th Gen i7 Thin & Light Lapt...,"₹69,999.00",7 Days Replacement,--,Sale starts on July 22
2,Visit the ASUS Store,"ASUS VivoBook 15 (2021), 15.6-inch (39.62 cm) ...",--,7 Days Replacement,--,In stock.
3,Visit the Dell Store,"Dell Inspiron 3525 Laptop, AMD Athlon Silver 3...",--,7 Days Replacement,"Monday, July 25",
4,Visit the Lenovo Store,Lenovo IdeaPad Slim 3 Intel Celeron N4020 15.6...,--,7 Days Replacement,--,In stock.
...,...,...,...,...,...,...
64,Visit the Acer Store,Acer Aspire 3 AMD 3020e Dual-core Processor 14...,--,7 Days Replacement,--,In stock.
65,Visit the HP Store,"HP Chromebook 14A G5, AMD A4 14-inch(35.6 cm) ...",--,7 Days Replacement,--,In stock.
66,Visit the Amazon Renewed Store,(Renewed) Dell 3330 Latitude 13.3 Inch Screen ...,"₹27,490.00",7 Days Replacement,--,In stock.
67,Brand: MI,Mi Notebook Ultra 3K Resolution Display Intel ...,--,7 Days Replacement,--,In stock.
68,Visit the Lenovo Store,Lenovo IdeaPad Slim 3 Intel Core i3 11th Gen 1...,--,7 Days Replacement,--,In stock.

In [10]:
df.to_csv("Scraped File",index=False)

In [11]:
driver.close()

# 3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [12]:
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()
driver.get('https://images.google.com/')

inp = ['fruits','cars','Machine Learning','Guitar','Cakes'] # input list

#Creating Empty lists
fruits=[]
cars=[]
ML=[]
Guitar=[]
Cakes=[]

lists = [] # list of empty lists

for i in inp:
    try:
        search_bar=driver.find_element(By.XPATH,'//*[@id="sbtc"]/div/div[2]/input') # Finding the search bar using it's xpath
    except NoSuchElementException:
        search_bar=driver.find_element(By.XPATH,'//input[@class="og3lId"]') # Finding the search bar using it's xpath
        
    search_bar.clear()
    search_bar.send_keys(i) # Inputing input keyword to search rock images
    
    try:
        button=driver.find_element(By.XPATH,'//*[@id="sbtc"]/button')  
    except NoSuchElementException:
        button=driver.find_element(By.XPATH,'//button[@class="rCGXm"]')
    button.click()
    
    
    img = driver.find_elements(By.XPATH,'//div[@class="bRMDJf islir"]/img')
    for k in img:
        try:
            source= k.get_attribute('src')
            if source is not None:
                if (source[0:4]=="http"):
                    lists.append(source)
        except NoSuchElementException:
            lists.append('-')
            

len(lists)            
#print(len(fruits),len(cars),len(ML),len(Guitar),len(Cakes))

105

In [16]:

fruits=lists[1:21]
cars=lists[22:42]
ML=lists[43:63]
Guitar=lists[64:84]
Cakes=lists[85:105]

print(len(fruits),len(cars),len(ML),len(Guitar),len(Cakes))

20 20 20 20 20

In [17]:
#creating a dataframe
df=pd.DataFrame({'Fruits':fruits,
                 'Cars':cars,
                 'Machine Learning':ML,
                 'Guitar':Guitar,
                 'Cakes':Cakes})

#printing dataframe
df.head()

,Fruits,Cars,Machine Learning,Guitar,Cakes
0,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
1,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
2,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
3,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
4,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...

# 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on
www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be 
scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, 
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the 
details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [19]:
# Connecting to webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

# opening the url
driver.get('https://www.flipkart.com')

#cancelling login window
search_btn = driver.find_element(By.XPATH,'//button[@class="_2KpZ6l _2doB4z"]')
search_btn.click()

# getting the input
search_inp = input("Enter the product: ")

# locating the search bar
search_bar = driver.find_element(By.XPATH,"//input[@class='_3704LK']")
search_bar.send_keys(search_inp)

# locating the search button
search_btn = driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
search_btn.click()

Enter the product: pixel 4A

In [20]:
# creating Empty variable to store our data:
brand = []
s_name = []
color = []
ram = []
rom = []
p_camera = []
s_camera = []
display_s = []
display_r = []
battery = []
price = []
url = []

In [21]:
# fetching the details

# extracting product name, brand name, colour.
for i in driver.find_elements(By.XPATH,"//div[@class='_4rR01T']"):
    s_name.append(i.text)
    name = s_name[-1].split() #extracting the brand name from the product name
    brand.append(name[0])
    a = s_name[-1][s_name[-1].find("(")+1:s_name[-1].rfind(")")]
    color.append(a.split(',')[0]) #extracting colour from the product name
    
# extracting the ram and rom.
for j in driver.find_elements(By.XPATH,"//ul[@class='_1xgFaf']/li[1]"):
    ram.append(j.text.split('|')[0])
    rom.append(j.text.split('|')[1])
    
# extracting primary and secondary camera
for k in driver.find_elements(By.XPATH,"//ul[@class='_1xgFaf']/li[3]"):
    if(len(k.text.split('|')) == 2):
        p_camera.append(k.text.split('|')[0])
        s_camera.append(k.text.split('|')[1])
    else:
        p_camera.append(k.text.split('|')[0])
        s_camera.append('--')

# extracting display size and display resolution
for l in driver.find_elements(By.XPATH,"//ul[@class='_1xgFaf']/li[2]"):
    s = l.text[l.text.find("(")+1:l.text.rfind(")")]
    display_s.append(s)
    r = l.text[l.text.find(")")+1:]
    display_r.append(r)
        
#extracting battery power.
for n in driver.find_elements(By.XPATH,"//ul[@class='_1xgFaf']/li[4]"):
    battery.append(n.text)
    
# extracting price
for o in driver.find_elements(By.XPATH,"//div[@class='_30jeq3 _1_WHN1']"):
    price.append(o.text)

# extracting url
for p in driver.find_elements(By.XPATH,"//a[@class='_1fQZEK']"):
    url.append(p.get_attribute('href'))

In [22]:
flipkart = pd.DataFrame({})
flipkart['Brand'] = brand
flipkart['Product description'] = s_name
flipkart['Colour'] = color
flipkart['RAM'] = ram
flipkart['ROM'] = rom
flipkart['Primary Camera'] = p_camera
flipkart['Secondary Camera'] = s_camera
flipkart['Display Size'] = display_s
flipkart['Display Resolution'] = display_r
flipkart['Battery'] = battery
flipkart['Price'] = price
flipkart['Product url'] = url

In [23]:
flipkart.head()

,Brand,Product description,Colour,RAM,ROM,Primary Camera,Secondary Camera,Display Size,Display Resolution,Battery,Price,Product url
0,Google,"Google Pixel 4a (Just Black, 128 GB)",Just Black,6 GB RAM,128 GB ROM,12.2MP Rear Camera,8MP Front Camera,5.81 inch,Full HD+ Display,3140 mAh Battery,"₹31,999",https://www.flipkart.com/google-pixel-4a-just-...
1,vivo,"vivo T1 44W (Starry Sky, 128 GB)",Starry Sky,4 GB RAM,128 GB ROM,50MP + 2MP + 2MP,16MP Front Camera,6.44 inch,Full HD+ AMOLED Display,5000 mAh Lithium Battery,"₹14,499",https://www.flipkart.com/vivo-t1-44w-starry-sk...
2,vivo,"vivo T1 44W (Starry Sky, 128 GB)",Starry Sky,6 GB RAM,128 GB ROM,50MP + 2MP + 2MP,16MP Front Camera,6.44 inch,Full HD+ AMOLED Display,5000 mAh Lithium Battery,"₹15,999",https://www.flipkart.com/vivo-t1-44w-starry-sk...
3,Infinix,"Infinix Smart 6 (Starry Purple, 64 GB)",Starry Purple,2 GB RAM,64 GB ROM,8 MP + Depth Lens,5MP Front Camera,6.6 inch,HD+ Display,5000 mAh Li-ion Polymer Battery,"₹7,499",https://www.flipkart.com/infinix-smart-6-starr...
4,vivo,"vivo T1 44W (Ice Dawn, 128 GB)",Ice Dawn,4 GB RAM,128 GB ROM,50MP + 2MP + 2MP,16MP Front Camera,6.44 inch,Full HD+ AMOLED Display,5000 mAh Lithium Battery,"₹14,499",https://www.flipkart.com/vivo-t1-44w-ice-dawn-...

In [24]:
flipkart.to_csv("Scraped mobile File",index=False)

In [25]:
driver.close()

# 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.¶

In [1]:
# Importing libraries
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

In [2]:
# Importing warings and ignoring waring if any present
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

# opening the url
driver.get('https://www.google.com/maps')

search_inp = input("Enter the city: ")
search_bar = driver.find_element(By.XPATH,"//input[@id='searchboxinput']") # locating search bar
search_bar.send_keys(search_inp)

# locating search button
search_btn = driver.find_element(By.XPATH,"//button[@id='searchbox-searchbutton']")
search_btn.click()

# getting the geospatial co-ordinates from the url
time.sleep(2)
geo = driver.current_url
r = geo[geo.find("@")+1:]
s = r[0:21]
s = s.split(',')
print(f'''Latitude: {s[0]}
Longitude: {s[1]}''')

# 6. Write a program to scrap details of all the funding deals for second quarter (i.e Jan 21 – March 21) from trak.in

In [4]:
#importing required libraries:

# Importing libraries
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

In [5]:
driver = webdriver.Chrome("chromedriver.exe")

In [6]:
# get webpage
driver.get("https://trak.in/")
time.sleep(2)
driver.maximize_window()

In [7]:
#click on funding deals and go to that page
fun_btn=driver.find_element(By.XPATH,"//li[@id='menu-item-51510']/a").get_attribute('href')
driver.get(fun_btn)

In [9]:
# Creating empty list
funding={}
funding["Date"]=[]
funding["Startup Name"]=[]
funding["Industry or Vertical"]=[]
funding["Sub Vertical"]=[]
funding["Location"]=[]
funding["Investor"]=[]
funding["Investment Type"]=[]
funding["Amount"]=[]

for i in range(54,57):


    # Scraping data of Date
    date_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[2]'.format(i))# {} and .format () used
    #so the number coming in function format(n) will replace {}
    for date in date_tags:
        funding['Date'].append(date.text)

    # Scraping data of Startup Name
    name_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[3]'.format(i))
    for name in name_tags:
        funding['Startup Name'].append(name.text)
    
    # Scraping data of Industry OR Vertical
    ind_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[4]'.format(i))
    for n in ind_tags:
        funding['Industry or Vertical'].append(n.text)
    
    # Scraping data of Sub-Vertical
    sv_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[5]'.format(i))
    for sv in sv_tags:
        funding['Sub Vertical'].append(sv.text)

    # Scraping data of Location
    loc_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[6]'.format(i))
    for loc in loc_tags:
        funding['Location'].append(loc.text)
    
    # Scraping data of Investor
    inv_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[7]'.format(i))
    for inv in inv_tags:
        funding['Investor'].append(inv.text)
        
    # Scraping data of Investment Type
    invt_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[8]'.format(i))
    for invt in invt_tags:
        funding['Investment Type'].append(invt.text)
    # Scraping data of Amount
    amt_tags = driver.find_elements(By.XPATH,'//table[@id="tablepress-{}"]/tbody/tr/td[9]'.format(i))
    for amt in amt_tags:
        funding['Amount'].append(amt.text)

In [10]:
details=pd.DataFrame(funding)
details

,Date,Startup Name,Industry or Vertical,Sub Vertical,Location,Investor,Investment Type,Amount
0,15/01/2021,Digit Insurance,Financial Services,Insurance Services,Bengaluru,"A91 Partners, Faering Capital, TVS Capital Funds",Venture,"1,80,00,000"
1,28/01/2021,Bombay Shaving Company,Consumer Goods Company,"Shave care, beard care, and skincare products",New Delhi,Reckitt Benckiser,Venture,"6,172,258.50"
2,19/01/2021,DeHaat,AgriTech Startup,online marketplace for farm products and services,Patna,Prosus Ventures,Series C,"30,000,000"
3,19/01/2021,Darwinbox,SaaS,HR Tech,Mumbai,Salesforce Ventures,Seed,"15,000,000"
4,18/01/2021,mfine,Health Tech Startup,AI-powered telemedicine mobile app,Bengaluru,Heritas Capital Management,Venture Round,"16,000,000"
5,18/01/2021,Udayy,EdTech,Online learning platform for kids in class 1-5,Gurgaon,Sequoia Capital,Seed Funding,"15,000,000"
6,11/01/2021,True Elements,Food Startup,Whole Food plant based Nashta,Pune,SIDBI Venture Capital,Series,"100,000,000"
7,13/01/2021,Saveo,B2B E-commerce,Pharmacies,Bengaluru,"Matrix Partners India, RTP Global, others",Seed,"4,000,000"
8,11/02/2021,Doubtnut,Edu Tech,E-Learning Platform,Gurgaon,"SIG Global, Sequoia Capital, WaterBridge Ventu...",Series B,"2,500,000"
9,22/02/2021,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,"Tiger Global, Kora",Venture,"250,000,000"
10,19/02/2021,Fingerlix,Hospitality,Semi-cooked food delivery app,Mumbai,"Rhodium Trust, Accel Partners and Swiggy",Series C,"2,747,045.20"
11,17/02/2021,Zolve,FinTech,Global Neobank Venture,Mumbai,Accel Partners and Lightspeed Venture Partners,Seed,"1,50,00,000"
12,15/02/2021,KreditBee,Finance,Digital lending platform,Bengaluru,Azim Premji’s PremjiInvest and South Korea’s M...,Series C,"75,000,000"
13,12/02/2021,Pepperfry,E-commerce,Multi-brand furniture brand,Mumbai,InnoVen Capital,Debt Financing,"4,773,958"
14,12/02/2021,Grofers,E-Commerce,Online supermarket,Gurgaon,SoftBank Vision Fund (SVF),Unspecified,"55,000,000"
15,09/02/2021,Nothing,Technology,Consumer Technology Venture,London,GV,Series A,"15,000,000"
16,09/02/2021,SplashLearn,EdTech,Game-based learning programme,Gurgaon,Owl Ventures,Series C,"18,000,000"
17,04/03/2021,DealShare,E-commerce,Online shopping platform,"Jaipur, Rajasthan",Innoven Capital,Debt Financing,"250,000,000"
18,31/03/2021,Uniphore,Technology,Conversational Service Automation (CSA),Palo Alto,Sorenson Capital Partners,Series D,"140,000,000"
19,30/03/2021,Dunzo,E-commerce,Hyper-local delivery app,Bengaluru,Krishtal Advisors Pte Ltd,Series E,"8,000,000"
20,30/03/2021,BYJU’S,Edu-tech,Online tutoring,Bengaluru,"MC Global Edtech, B Capital, Baron, others",Series F,"460,000,000"
21,23/03/2021,SkilloVilla,Edu-tech,Career and job-oriented upskilling.,Bengaluru,"Titan Capital, others",Seed,"300,000,000"
22,25/03/2021,CityMall,E-commerce,Social ecommerce and online grocery platform,Gurgaon,Accel Partners,Series A,"11,000,000"
23,26/03/2021,DotPe,FinTech,Commerce and payments platform to offline ente...,Gurgaon,PayU,Series A,"27,500,000"

# 7. Write a program to scrap all the available details of best gaming laptops from digit.in

In [16]:
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

In [17]:
driver.get("https://www.digit.in/")

In [18]:
driver.find_element(By.XPATH,"//div[@class='listing_container']//ul//li[9]").click()
time.sleep(3)

In [19]:
#Creating empty lists
Laptop_Name = []
Operating_sys = []
Display = []
Processor = []
Memory = []
Weight = []
Dimensions = []
Graph_proc = []
Price = []
# Scraping the data of laptop names
laptop_name= driver.find_elements(By.XPATH,"//div[@class='right-container']/div/a/h3")
for name in laptop_name:
    Laptop_Name.append(name.text)
    
    
#Scraping the data of operating system
try:
    op_sys = driver.find_elements(By.XPATH,"//div[@class='product-detail']/div/ul/li[1]/div/div")
    for os in op_sys:
        Operating_sys.append(os.text)
except NoSuchElementException:
    pass


#Scraping data of display of the laptop
try:
    display= driver.find_elements(By.XPATH,"//div[@class='product-detail']/div/ul/li[2]/div/div")
    for disp in display:
        Display.append(disp.text)
except NoSuchElementException:
    pass


#Scraping data of Processor
try:
    processor = driver.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[5]/td[3]")
    for pro in processor:
        Processor.append(pro.text)
except NoSuchElementException:
    pass

#Scraping data of memory
try:
    memory = driver.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[6]/td[3]")
    for memo in memory:
        Memory.append(memo.text)
except NoSuchElementException:
    pass



#Scraping data of dimensions
try:
    dimension = driver.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[8]/td[3]")
    for dim in dimension:
        Dimensions.append(dim.text)
except NoSuchElementException:
    pass


#Scraping data of Graph processor
try:
    graph = driver.find_elements(By.XPATH,"//div[@class='Spcs-details'][1]/table/tbody/tr[7]/td[3]")
    for gra in graph:
        Graph_proc.append(gra.text)
except NoSuchElementException:
    pass


#Scraping data of price
try:
    price = driver.find_elements(By.XPATH,"//td[@class='smprice']")
    for pri in price:
        Price.append(pri.text.replace('₹','Rs '))
except NoSuchElementException:
    pass

In [20]:
print(len(Laptop_Name),len(Operating_sys),len(Display),len(Processor),len(Memory),len(Dimensions),len(Graph_proc),len(Price))

10 10 10 10 10 10 10 10

In [21]:
Gaming_Laptop=pd.DataFrame({})
Gaming_Laptop['Laptop Name'] = Laptop_Name
Gaming_Laptop['Operating system'] = Operating_sys
Gaming_Laptop['Display'] = Display
Gaming_Laptop['Processor'] = Processor
Gaming_Laptop['Memory'] = Memory
Gaming_Laptop['Dimensions'] = Dimensions
Gaming_Laptop['Graphical Processor'] = Graph_proc
Gaming_Laptop['Price'] = Price
Gaming_Laptop

,Laptop Name,Operating system,Display,Processor,Memory,Dimensions,Graphical Processor,Price
0,MSI TITAN GT77-12UHS,WINDOWS 11 HOME OS,"17.3"" (3840 X 2160) DISPLAY",Windows 11 Home,64 GB DDR5 RAM & 2 TB SSD,397 x 330 x 23 mm dimension & 3.3 kg weight,16 GB DDR6 NVIDIA GeForce RTX 3080 Ti Graphics...,N/A
1,ALIENWARE X17 R2,WINDOWS 11 HOME OS,"17.3"" (1920X1080) DISPLAY",Windows 11 Home,32 GB DDR5 RAM & 1 TB SSD,399.23 x 299.57 x 14.75 mm dimension & 3.02 kg...,"16 GB DDR6 NVIDIA GeForce RTX 3080 Ti, Graphic...","Rs 389,990"
2,ACER PREDATOR TRITON 500 SE PT516-52S,WINDOWS 11 HOME OS,"16"" (2560 X 1600) DISPLAY",Windows 11 Home,32 GB DDR5 RAM & 2 TB SSD,358 x 262 x 19.9 mm dimension & 2.4 kg weight,8 GB DDR6 NVIDIA GeForce RTXTM 3070 Ti Graphic...,"Rs 300,000"
3,OMEN BY HP (16-B1371TX),WINDOWS 11 HOME OS,"16.1"" (2560 X 1440) DISPLAY",Windows 11 Home,8 GB DDR5 RAM & 1 TB SSD,369 x 248 x 23 mm dimension & 2.32 kg weight,8 GB GDDR6 NVIDIA GeForce RTX 3070 Graphics card,"Rs 170,990"
4,ACER PREDATOR HELIOS 300 AN515-45 (NH.QBRSI.0,WINDOWS 11 HOME OS,"15.6"" (2560 X 1440) DISPLAY",Windows 11 Home,16 GB DDR4 RAM & 512 GB SSD,363 x 255 x 23.9 mm dimension & 2.4 kg weight,8 GB DDR6 NVIDIA GeForce RTX 3070 Graphics card,"Rs 172,999"
5,MSI DELTA 15 (A5EFK-083IN),WINDOWS 11 HOME OS,"15.6"" (1920 X 1080) DISPLAY",Windows 11 Home,16 GB DDR4 RAM & 1 TB SSD,357 x 247 x 19 mm dimension & 1.9 kg weight,10 GB DDR6 AMD Radeon RX 6700M Graphics card,"Rs 188,990"
6,OMEN BY HP (16-C0141AX),WINDOWS 11 HOME OS,"16.1"" (2560 X 1440) DISPLAY",Windows 11 Home,16 GB DDR4 RAM & 1 TB NVMe,36.92 x 24.8 x 2.3 mm dimension & 2.3 kg weight,8 GB GDDR6 AMD Radeon™ RX 6600M Graphics card,"Rs 129,899"
7,LENOVO LEGION 5I PRO (82RF00MGIN),WINDOWS 11 HOME OS,"16"" (2560 X 1600) DISPLAY",Windows 11 Home,16 GB DDR5 RAM & 1 TB SSD,359.9 x 264.4 x 19.9 mm dimension & 2.5 kg weight,6 GB DDR6 NVIDIA GeForce RTX 3060 Graphics card,"Rs 230,890"
8,ALIENWARE M15 R5 RYZEN EDITION ICC-C780001WIN,WINDOWS 11 HOME OS,"15.6"" (1920 X 1080) DISPLAY",Windows 11 Home,16 GB DDR4 RAM & 512 GB SSD,356.2 x 272.5 x 22.85 mm dimension & 2.69 kg w...,6 GB DDR6 NVIDIA GeForce RTX 3060 Graphics card,"Rs 144,990"
9,LENOVO SLIM 7 GEN 6 (82K8002JIN),WINDOWS 11 HOME OS,15.6 MP | NA DISPLAY,Windows 11 Home,16 GB DDR4 RAM & 1 TB SSD,356 x 252 x 16 mm dimension & 1.9 kg weight,6 GB DDR6 NVIDIA GeForce 3060 Max-Q Graphics card,"Rs 142,990"

# 8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [22]:
# Connecting to webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

# opening the url
driver.get('https://www.forbes.com/')

# clicking on options
driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/button[1]').click()

In [23]:
#clickng on All Billionaires option 

billionaires=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[3]/ul/li[1]')
billionaires.click()

all_billionaires=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[3]/ul/li[1]/div[2]/ul/li[2]/a')
all_billionaires.click()

In [24]:
# Scrapping required details:

#creating empty lists:
Rank = []
Name = []
Net_Worth = []
Age = []
Citizenship = []
Source = []
Industry = []

# Scraping Ranks

try:
    R = driver.find_elements(By.XPATH,'//div[@class="rank"]')
    for i in R:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")

#Scraping Names
try:
    N = driver.find_elements(By.XPATH,'//div[@class="personName"]')
    for i in N:
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")

#Scraping Net Worth
try:
    NW = driver.find_elements(By.XPATH,'//div[@class="netWorth"]')
    for i in NW:
        Net_Worth.append(i.text)
except NoSuchElementException:
    Net_Worth.append("-")
    
#Scraping Age
try:
    A = driver.find_elements(By.XPATH,'//div[@class="age"]')
    for i in A:
        Age.append(i.text)
except NoSuchElementException:
    Age.append("-")

#Scraping country Of Citizenship
try:
    C = driver.find_elements(By.XPATH,'//div[@class="countryOfCitizenship"]')
    for i in C:
        Citizenship.append(i.text)
except NoSuchElementException:
    Citizenship.append("-")
    
#Scraping Source
try:
    S = driver.find_elements(By.XPATH,'//div[@class="source"]')
    for i in S:
        Source.append(i.text)
except NoSuchElementException:
    Source.append("-")

#Scraping Industry
try:
    I = driver.find_elements(By.XPATH,'//div[@class="category"]')
    for i in I:
        Industry.append(i.text)
except NoSuchElementException:
    Industry.append("-")

In [25]:
print(len(Rank),len(Name),len(Net_Worth),len(Age),len(Citizenship),len(Source),len(Industry))

200 200 200 200 200 200 200

In [26]:
df = pd.DataFrame({'Rank':Rank,
                   'Name':Name,
                   'Net_Worth':Net_Worth,
                   'Age':Age,
                   'Citizenship':Citizenship,
                   'Source':Source,
                   'Industry':Industry})
df

,Rank,Name,Net_Worth,Age,Citizenship,Source,Industry
0,1.,Elon Musk,$219 B,50,United States,"Tesla, SpaceX",Automotive
1,2.,Jeff Bezos,$171 B,58,United States,Amazon,Technology
2,3.,Bernard Arnault & family,$158 B,73,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$129 B,66,United States,Microsoft,Technology
4,5.,Warren Buffett,$118 B,91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,192.,Marcel Herrmann Telles,$10.3 B,72,Brazil,beer,Food & Beverage
196,197.,Leon Black,$10 B,70,United States,private equity,Finance & Investments
197,197.,Joe Gebbia,$10 B,40,United States,Airbnb,Technology
198,197.,David Geffen,$10 B,79,United States,"movies, record labels",Media & Entertainment
199,197.,Yu Renrong,$10 B,56,China,semiconductors,Manufacturing

# 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [27]:
# Importing libraries
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

In [28]:
# Connecting to webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

# opening the url
driver.get('https://www.youtube.com/')

# Clicking on any Random Video
driver.find_element(By.XPATH,'/html/body/ytd-app/div/ytd-page-manager/ytd-browse/ytd-two-column-browse-results-renderer/div[1]/ytd-rich-grid-renderer/div[6]/ytd-rich-grid-row[2]/div/ytd-rich-item-renderer[2]/div/ytd-rich-grid-media/div[1]/div[2]').click()

In [29]:
# Pausing the video
driver.find_element(By.XPATH,'/html/body/ytd-app/div/ytd-page-manager/ytd-watch-flexy/div[5]/div[1]/div/div[1]').click()

In [37]:
# Scrapping required details:

#Creating Empty Lists
Comment = []
Upvote = []
Time = []

# Scraping Comments 
C = driver.find_elements(By.ID,"content-text")
for i in C:
    Comment.append(i.text)
    
#Scrapping Upvotes
try:
    U = driver.find_elements(By.XPATH,'//span[@id="vote-count-middle"]')
    for i in U:
        Upvote.append(i.text)
except NoSuchElementException:
    Upvote.append("-")

#Scrapping when comment was posted 
try:
    T = driver.find_elements(By.XPATH,'//a[@class="yt-simple-endpoint style-scope yt-formatted-string"]')
    for i in T:
        Time.append(i.text)
except NoSuchElementException:
    Time.append("-")

In [38]:
print(len(Comment),len(Upvote),len(Time))

713 713 862

In [39]:
df = pd.DataFrame({'Comments':Comment[:500],
                   'Comment upvote':Upvote[:500],
                   'time when comment was posted':Time[100:600]})

df

,Comments,Comment upvote,time when comment was posted
0,"Jin jin ka result aaya hai aaj, congratulation...",5K,1 day ago
1,This Man Has Proved Everyone That He Can Enter...,169,1 day ago (edited)
2,This was so hilariousCan't stop laughingYour T...,109,18 hours ago
3,I just don't want this video to end! Seeing yo...,120,1 hour ago
4,Like literally no one can stop his laughter af...,13,1 day ago
...,...,...,...
495,This 13:33 min were the bestt!literally can't ...,6,1 day ago
496,Try not to laugh Challenge Me Sabne Hi Hasa Hai,,14 hours ago
497,Love your vlogs,1,0:45
498,Best part faisu punchar shop,1,1 day ago
499,Bruhhh this is seriously a laughing sessionI w...,9,1 day ago

# 10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [47]:
# Importing libraries
import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import requests
import re

In [48]:
# Connecting to webdriver
driver = webdriver.Chrome("chromedriver.exe")
driver.maximize_window()

# opening the url
driver.get('https://www.hostelworld.com/')

In [50]:
#choosing frist option
driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[1]/div[4]/div/div/div[2]/div/div[1]/div[2]/a[1]/div/h2').click()

In [53]:
# Scrapping required details: 
#scraping hostel name, distance from city centre, ratings, total reviews, overall reviews, 
#privates from price, dorms from price, facilities and property description.

#Creating Empty Lists
Name = []
Distance = []
Rating = []
Reviews = []
Overall = []
Privates = []
Dorms = []
Facilities = []
Property = []


# Scraping Names 
N = driver.find_elements(By.XPATH,'//h2[@class="title title-6"]')
for i in N:
    Name.append(i.text)
    
#Scrapping distance from city centre
try:
    D = driver.find_elements(By.XPATH,'//span[@class="description"]')
    for i in D:
        Distance.append(i.text)
except NoSuchElementException:
    Distance.append("-")

#Scrapping ratings
try:
    RT = driver.find_elements(By.XPATH,'//div[@class="rating rating-summary-container big"]')
    for i in RT:
        Rating.append(i.text[:][0:3])
except NoSuchElementException:
    Rating.append("-")
    
#Scrapping total reviews
try:
    RV = driver.find_elements(By.XPATH,'//div[@class="reviews"]')
    for i in RV:
        Reviews.append(i.text)
except NoSuchElementException:
    Reviews.append("-")
    
#Scrapping overall reviews
try:
    O = driver.find_elements(By.XPATH,'//div[@class="keyword"]')
    for i in O:
        Overall.append(i.text)
except NoSuchElementException:
    Overall.append("-")
    
#Scrapping privates from price
P = driver.find_elements(By.XPATH,'//div[@class="price-col"]')[0::2]
for i in P:
    Privates.append(i.text.replace('\n',': ').replace('No Privates Available','NaN'))
       
#Scrapping Dorms from price
P = driver.find_elements(By.XPATH,'//div[@class="price-col"]')[1::2]
for i in P:
    Dorms.append(i.text.replace('\n',': ').replace('No Dorms Available','NaN'))
    
#Scrapping Facilities
try:
    F = driver.find_elements(By.XPATH,'//div[@class="facilities-label facilities"]')
    for i in F:
        Facilities.append(i.text.replace('\n',', '))
except NoSuchElementException:
    Facilities.append("-")
    
#Scrapping property description.
try:
    PD = driver.find_elements(By.XPATH,'//div[@class="rating-factors prop-card-tablet rating-factors small"]')
    for i in PD:
        Property.append(i.text.replace('\n',', '))
except NoSuchElementException:
    Property.append("-")

In [54]:
print(len(Name),len(Distance),len(Rating),len(Reviews),len(Privates),len(Dorms),len(Facilities),len(Property))

30 30 30 30 30 30 30 30

In [55]:
#scraping hostel name, distance from city centre, ratings, total reviews, overall reviews, 
#privates from price, dorms from price, facilities and property description.
# Creating Data Frame 
df = pd.DataFrame({'Hostel name':Name,
                   'Distance from city centre':Distance,
                   'Rating':Rating,
                   'Total reviews':Reviews,
                   'Privates from price':Privates,
                   'Dorms from price':Dorms,
                   'Facilities':Facilities,
                   'Property description':Property})
df

,Hostel name,Distance from city centre,Rating,Total reviews,Privates from price,Dorms from price,Facilities,Property description
0,PubLove @ The Rose & Crown,Hostel - 1.6km from city centre,8.0,139 Total Reviews,NaN,Dorms From: Rs5349,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Superb Staff, Awesome Cleanl..."
1,Astor Kensington,Hostel - 4.9km from city centre,8.1,6390 Total Reviews,NaN,Dorms From: Rs1826,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Superb Staff, Excellent Clea..."
2,Astor Victoria,Hostel - 1.8km from city centre,7.7,14782 Total Reviews,NaN,Dorms From: Rs1730,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Superb Staff, Awesome Cleanl..."
3,"PubLove @ The Exmouth Arms, Euston",Hostel - 3.4km from city centre,7.0,1034 Total Reviews,NaN,Dorms From: Rs4388,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Marvellous Staff, Awesome Cl..."
4,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,6.6,255 Total Reviews,NaN,Dorms From: Rs3075,"Free WiFi, Follows Covid-19 sanitation guidance","Great Location, Brilliant Staff"
5,Park Villa,Hostel - 6.3km from city centre,7.9,873 Total Reviews,NaN,Dorms From: Rs4017,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Superb Staff, Excellent Clea..."
6,Saint James Backpackers,Hostel - 5.5km from city centre,6.6,1815 Total Reviews,Privates From: Rs10591.55 Rs10062,Dorms From: Rs2498.36 Rs2373,"Free WiFi, Free Breakfast, Follows Covid-19 sa...","Wonderful Location, Marvellous Staff"
7,Kensal Green Backpackers,Hostel - 8.2km from city centre,4.7,3638 Total Reviews,NaN,Dorms From: Rs1602,Follows Covid-19 sanitation guidance,
8,"PubLove @ The Green Man, Paddington",Hostel - 4.3km from city centre,7.7,418 Total Reviews,Privates From: Rs24503,Dorms From: Rs2626,"Free WiFi, Follows Covid-19 sanitation guidance","Perfect Location, Superb Staff, Excellent Clea..."
9,Book a Bed Hostels,Hostel - 6.9km from city centre,7.0,1198 Total Reviews,Privates From: Rs9512.97 Rs8562,Dorms From: Rs2164.18 Rs1948,Free WiFi,"Great Location, Marvellous Staff, Awesome Clea..."
10,Britannia Inn Hotel,Hotel - 14.5km from city centre,8.2,22 Total Reviews,Privates From: Rs6726,NaN,"Free Breakfast, Follows Covid-19 sanitation gu...","Wonderful Location, Superb Staff, Excellent Cl..."
11,The Backpackshack,Hostel - 10.9km from city centre,8.8,731 Total Reviews,Privates From: Rs5669,NaN,Free WiFi,"Wonderful Location, Superb Staff, Fantastic Cl..."
12,Barry House,Bed and Breakfast - 4.2km from city centre,6.9,15 Total Reviews,Privates From: Rs9833,NaN,"Free WiFi, Free Breakfast","Perfect Location, Marvellous Staff, Awesome Cl..."
13,London House Hotel,Hotel - 5.3km from city centre,8.8,1382 Total Reviews,Privates From: Rs28308.29 Rs19816,NaN,Free WiFi,"Perfect Location, Superb Staff, Fantastic Clea..."
14,Elmwood Hotel,Hotel - 3.2km from city centre,6.1,116 Total Reviews,Privates From: Rs8968,NaN,,"Perfect Location, Awesome Cleanliness"
15,Kip Hotel,Hotel - 6.8km from city centre,6.6,54 Total Reviews,Privates From: Rs8520,NaN,Free WiFi,"Nice Location, Superb Staff, Excellent Cleanli..."
16,The London Home Hostel,Hostel - 8.2km from city centre,3.8,258 Total Reviews,Privates From: Rs6246,Dorms From: Rs2402,Free WiFi,
17,Cranbrook Hotel,Hotel - 14.8km from city centre,No,58 Total Reviews,Privates From: Rs16560,NaN,"Free Breakfast, Follows Covid-19 sanitation gu...",
18,Belgravia Hotel,Hotel - 2.4km from city centre,8.9,8 Total Reviews,Privates From: Rs8245,NaN,Free WiFi,"Perfect Location, Superb Staff, Excellent Clea..."
19,Hyde Park Court Hotel,Hotel - 4.3km from city centre,4.2,139 Total Reviews,Privates From: Rs11179,NaN,"Free WiFi, Free Breakfast",Wonderful Location
20,City Hotel Carlton,Hotel - 1.8km from city centre,6.7,40 Total Reviews,Privates From: Rs12171,NaN,,"Great Location, Marvellous Staff"
21,Hotel Shepherds Bush London,Hotel - 7.6km from city centre,No,0 Total Reviews,Privates From: Rs18295.96 Rs14820,NaN,"Free WiFi, Follows Covid-19 sanitation guidance",
22,Tony's House Hotel,Hotel - 4.3km from city centre,No,406 Total Reviews,Privates From: Rs11563,NaN,Free Breakfast,
23,All Star Private Studios,Apartment - 9.1km from city centre,No,150 Total Reviews,Privates From: Rs8648,Dorms From: Rs2402,Free WiFi,
24,Beaconsfield,Hotel - 8.6km from city centre,No,28 Total Reviews,Privates From: Rs8232,NaN,Free WiFi,
25,Park Hotel Essex,Hotel - 24.1km from city centre,8.0,109 Total Reviews,Privates From: Rs24503,NaN,"Free Breakfast, Follows Covid-19 sanitation gu...","Wonderful Location, Marvellous Staff, Excellen..."
26,London Town Hotel,Hotel - 5.4km from city centre,No,61 Total Reviews,Privates From: Rs12492,NaN,Free WiFi,
27,Wellesley Hotel,Hotel - 14.7km from city centre,No,0 Total Reviews,Privates From: Rs8648,NaN,Free WiFi,
28,TLK Apartments & Hotel,Hotel - 19.9km from city centre,No,0 Total Reviews,Privates From: Rs10810,NaN,Free WiFi,
29,Park Hotel,Hotel - 4.9km from city centre,No,0 Total Reviews,Privates From: Rs16816,NaN,Free WiFi,

# ------------------XXXXXXXXXXXXXXXXXXXXXXX-------------------------------------------